### PR TITLE
Better translations of Task, Tasklist, Assignee and Owner

### PR DESCRIPTION
**Pull request by scepbjoern**
As asked by @fh48  in https://github.com/camunda/camunda-webapp-translations/pull/25#issuecomment-424238221 I translated the words in the title to better equivalents in German. The only exception is "Task-Variable", which I left as is and not translated to "Aufgaben-Variable".

### CODE REVIEW

**Comment by ThorbenLindhauer** [comment]
@tasso94 let's review this together

**Comment by tasso94** [comment]
Hi @scepbjoern,

we have reviewed your changes internally. I would like to share the outcome with you and kindly ask you to adjust your pull request accordingly:
* Tasklist has a different target group compared with Admin and Cockpit: Users of Admin and Cockpit have a more technical background, whereas users of Tasklist are predominantly business users. Therefore, in Admin and Cockpit we would like to stick to the technical terms (e. g. Task, Assignee, External Tasks etc.). Like this, it is easier for technical users to map the respective labels with the documented terms in the documentation (which is currently only available in the english language).
* App names (i. e. Tasklist, Cockpit, Admin) should not be translated as these are well established terms in context of the product
* In Tasklist, the word "owner" should be translated to "Besitzer"
* In Tasklist, the word "assignee" should be translated to "Bearbeiter"

Cheers,
Tassilo

**Comment by scepbjoern** [comment]
Hi Tassilo

I added a new commit containing the proposed improvements.

Cheers,
Björn

**Comment by tasso94** [comment]
Hi @scepbjoern,

I've just squashed your changes and merged it with the master branch.

Thanks for your contribution!

Cheers,
Tassilo

**Pull request closed without merging**
