### PR TITLE
Tool SynchroTranslation, detect missing keys, and propose completion

### PR DESCRIPTION
**Pull request by pierre-yves-monnet**
The tool SynchroTranslation compare each dictionary from the reference dictionary (English by default)
* detect all missing keys, all incoherences
* propose for each missing translation of a sentence. This sentence can be calculated from another sentence, or via Google Translation.

The reviewer can check and accept the different propositions to have a complete translation.

### CODE REVIEW

**Comment by tasso94** [comment]
Hi @pierre-yves-monnet,

Thanks for raising this PR. We will have a look and provide you with review feedback.

Stay tuned!

Best,
Tassilo

**Comment by koevskinikola** [comment]
Hi @pierre-yves-monnet,

Thank you for this contribution, and apologies for the long delay with my reply.

I think your contribution is pretty useful. However, I have several reasons why I don't think the `camunda-webapp-translations` repository is the correct place for it.

1. The AP team currently owns this repository. This means maintenance, versioning, and reviews of any new PRs to this repo. If we merge this new Java project, the AP team will also need to maintain this new codebase. This is a larger process, for which multiple parties need to agree, and the whole team needs to be aware of it.
2. We also include this repo in our release process. Adding a Java project to it will make our release process more complex (regarding this repo).
3. Finally, your changes make the root directory of this repo a Maven project. I wouldn't recommend it since your contribution is intended as a helper tool for translation contributions. It would be better if the project is in a separate directory.

My suggestion would be to develop this project as a community extension and provide it as a repo in https://github.com/camunda-community-hub. This would allow the Camunda community to contribute to it, and if the project gains enough traction, we can adopt it and start providing support for it.

Once you have it set up as a standalone project, we can add a link to it in the README here, so interested contributors can find it and use it.

What do you think?

Best,
Nikola

**Comment by koevskinikola** [comment]
I'm closing this PR. See https://github.com/camunda/camunda-webapp-translations/pull/134#issuecomment-1029799242 for more details.

**Comment by pierre-yves-monnet** [comment]
Hello Nikola,

I perfectly understand, and I will do that (create a new repo and put the translation tool there).

Thank you,

(PS: the tool shows some missing translation in german :-) ).

**Pull request closed without merging**
