### PR TITLE
Added Turkish translation file for tasklist

### PR DESCRIPTION
**Pull request by elifkus**

### CODE REVIEW

**Comment by elifkus** [comment]
I signed the license agreement online. But there is a warning saying that my account could not be associated. How come I could sign the document then?

**Comment by tasso94** [comment]
Hi @elifkus,

Thanks for your contribution.

The problem is that you committed your changes with the email address `elif***@h***lik.com`. However, this email address is not linked with your GitHub account. Please make sure to commit the changes with your GitHub email or add the email address from your commit to GitHub.

Best,
Tassilo

**Comment by tasso94** [comment]
Related ticket: CAM-11947

**Comment by elifkus** [comment]
Thank you. :) @tasso94  I updated it.

**Comment by tasso94** [comment]
Hi @elifkus,

Thank you for your contribution again. 🙂 

I've merged the Turkish language for Tasklist with the master branch.

Best,
Tassilo

**Pull request merged**
