### PR TITLE
tasklist/ru.json 7.15.0 -> 7.18.0

### PR DESCRIPTION
**Pull request by AnatolyKostrikov**
#162 

Please note, the translation was carried out without checking the context of the phrase in the Tasklist's UI. There are several doubts. Testing of this translation in the context of the User Journey is only in plans. I suppose some additions after testing.

From **ru7.15.0** and **en7.18.0** to **ru7.18.0**. 

Total phrases listed in the commit comment are 419 and 34% of them was changed:
- Added 4,
- Deleted 0,
- Unchanged 275,
- Updated 140.

### CODE REVIEW

**Comment by yanavasileva** [comment]
@AnatolyKostrikov is the PR ready for a review? Considering the mention WIP state:
> Testing of this translation in the context of the User Journey is only in plans.

**Review by AnatolyKostrikov — COMMENTED** [review]
@yanavasileva Yana, hi. 

> is the PR ready for a review? Considering the mention WIP state:
> Testing of this translation in the context of the User Journey is only in plans.

Unfortunately, as for now my personal plans have changed. I do not have Camunda Tasks module in my nearest personal sprints. But I hope to return to Tasks' UI testing some day. So **the Pull Request is ready for the review**, no updates expected. Except the following question. 

8 duplicate labels present in the file v7.15.0 [tasklist/ru.json](https://github.com/camunda/camunda-webapp-translations/raw/master/tasklist/ru.json).
Should I remove these duplicates?

|#|label|en|ru|
|:--:|:--|:--|:--|
|1|ASSIGNEE|Assignee|Ответственный|
||assignee|Assignee|Ответственный|
|||||
|2|COMMENT|Comment|Комментарий|
||Comment|Comment|Комментарий|
|||||
|3|COMPLETE|Complete|Выполненная|
||Complete|Complete|Выполнить|
|||||
|4|DELETE|Delete|Удалить|
||Delete|Delete|Удалить|
||delete|Delete|Удалить|
|||||
|5|DESCRIPTION|Description|Описание|
||description|Description|Описание|
|||||
|6|NAME|Name|Наименование|
||name|Name|Наименование|
|||||
|7|OWNER|Owner|Владелец|
||owner|Owner|Владелец|
|||||
|8|priority|Priority|Приоритет|
||PRIORITY|Priority|Приоритет|

**Comment by tasso94** [comment]
Hi @AnatolyKostrikov,

This repository will be moved into [Camunda's Community Hub](https://github.com/camunda-community-hub/).

Please reopen your pull request at https://github.com/camunda-community-hub/camunda-7-webapp-translations.

Best,
Tassilo

**Comment by AnatolyKostrikov** [comment]
[Here it is](https://github.com/camunda-community-hub/camunda-7-webapp-translations/pull/4), Tassilo.

**Pull request closed without merging**
