### PR TITLE
[CAM-10935] Camunda Tasklist for 7.11 in pt-BR

### PR DESCRIPTION
**Pull request by marciojv**
- Tasklist Review for Camunda 7.11.
- missing translation correction in welcome.

### CODE REVIEW

**Comment by mboskamp** [comment]
Hi @marciojv,
thank you for your contribution. We will have a look into the changes you made and come back to you shortly. I have created [CAM-10935](https://app.camunda.com/jira/browse/CAM-10935) to track the progress.

Cheers,
Miklas

**Comment by marstamm** [comment]
Hi @marciojv ,

I see that you have begun to translate Cockpit as well. If it's okay with you I'll keep this PR open for now. Feel free to ping me if you have any questions or the PR is ready to be merged :)

**Comment by marciojv** [comment]
I  marstamm, It should take a while, but I'll be done soon!

**Comment by marciojv** [comment]
Finished! @marstamm 
Now Camunda Cockpit in Portuguese Brazilian!

**Comment by marciojv** [comment]
Finished! @marstamm 
Now Camunda Cockpit in Portuguese Brazilian!

**Comment by marciojv** [comment]
Finished! @marstamm
Now Camunda Cockpit in Portuguese Brazilian!

**Comment by marstamm** [comment]
Thank you very much for your work. It is merged so everyone can find it :)

**Pull request merged**
