### PR TITLE
Update camunda 7.17 Translate for pt_BR!

### PR DESCRIPTION
**Pull request by marciojv**
Hello, update cockpit, tasklist and Admin UI.

### CODE REVIEW

**Comment by danielkelemen** [comment]
Hi @marciojv!
Thank you for your PR, we'll have a look as soon as possible and provide feedback.

**Comment by marciojv** [comment]
Hello @danielkelemen you look this PR ? #hacktoberfes

**Comment by danielkelemen** [comment]
@marciojv Yes, sorry for the delay. I will look at your PR this week and merge.

**Review by danielkelemen — APPROVED** [review]
Looks good to me!

**Pull request merged**
