### PR TITLE
CAM-14769: Improve the safety of executing a batch operation on the Batch Operation page

### PR DESCRIPTION
**Pull request by cliftondavies**
related to CAM-14769

### CODE REVIEW

**Review by tasso94 — COMMENTED** [review]
It is a little bit easier for the reviewer to have all translation tokens of a feature in a single PR. Otherwise, I need to cherry-pick multiple commits onto a single branch which is a little bit annoying.

**Review by tasso94 — APPROVED** [review]
Looks good.

**Comment by cliftondavies** [comment]
> It is a little bit easier for the reviewer to have all translation tokens of a feature in a single PR. Otherwise, I need to cherry-pick multiple commits onto a single branch which is a little bit annoying.

@tasso94, so for the Safe Bulk Operations feature this would mean having translations across all sub-tasks in a single PR, right?

**Comment by tasso94** [comment]
@cliftondavies,
> so for the Safe Bulk Operations feature, this would mean having translations across all sub-tasks in a single PR, right?
I don't think this can be generalized. It depends on the concrete situation.

In this specific case, CAM-14769 strongly depends on CAM-14702 since CAM-14769 references the `cam-widget-selection-type` directive in the code, but the code itself is part of CAM-14702. So it doesn't make sense to review or test each ticket in isolation. 

I think it would have been possible to work on both tickets in isolation without any dependencies on each other, but since you decided otherwise (which is perfectly fine; I think there is no "right" or "wrong" how you create PRs based on the tickets you are working on).

**Comment by tasso94** [comment]
To complete my last sentence:

... it would have been easier to have one PR with all translation changes affecting both tickets CAM-14769 and CAM-14702.

**Comment by cliftondavies** [comment]
Agreed. I'll be mindful of such scenarios going forward.

**Pull request merged**
