### PR TITLE
Italian tasklist translation

### PR DESCRIPTION
**Pull request by arkanoid87**
my first attempt in translating tasklist to italian language.

Not really sure if I took the right path on every token, but it's consistent from top to bottom.

### CODE REVIEW

**Comment by marstamm** [comment]
Hi @arkanoid87 ,

thank you for your contribution. The translations really help other users.

Unfortunately, I cannot merge it without a signed CLA. You will still be named as the author of the commit and as contributor in the readme.

Speaking of, please also add the new available language to the `README.md`

Cheers
Martin

**Comment by arkanoid87** [comment]
I think I've made a mess with the git user/mail and stuff, as I though to have already signed it. Solving now.

**Comment by arkanoid87** [comment]
ok, I officially made a mess with this repo while trying to edit the email pushed with the commit. Sorry :-/

**Comment by marstamm** [comment]
Don't worry ^^

looks like you have to rebase and force push your branch. Take your time and ping me if you're ready

**Comment by arkanoid87** [comment]
everything should be ok now

**Comment by marstamm** [comment]
Great, thank you

**Pull request merged**
