### PR TITLE
Update Portuguese Brazilian for 7.15

### PR DESCRIPTION
**Pull request by marciojv**
Update Translate Admin.Taslkist and Welcome.

### CODE REVIEW

**Comment by marciojv** [comment]
@tasso94 this is new PR correct now!

**Comment by tasso94** [comment]
Hi @marciojv,

Cool! I will check it soon 🙂 👍 

Stay tuned!

**Comment by marciojv** [comment]
this PR is ok @tasso94 ? Anything else you have to add? 
Att.

**Comment by tasso94** [comment]
Hi @marciojv,

Shallowly checking your contribution, it looks fine. However, I couldn't have a closer look so far.

Please stay tuned, and I'll give you feedback as soon as possible.

Best,
Tassilo

**Review by tasso94 — APPROVED** [review]
Thank you for your contribution! Looks good to me 🙂  👍 
I've merged it with the master branch 🚀

**Pull request merged**
