### PR TITLE
Update Translate Camunda Portuguese Brazilian for 7.15

### PR DESCRIPTION
**Pull request by marciojv**
Update Translate Admin.Taslkist and Welcome.

### CODE REVIEW

**Comment by tasso94** [comment]
Hi @marciojv,

Thank you for your contribution. I will have a look soon.

Stay tuned!

Best,
Tassilo

**Comment by tasso94** [comment]
Hi @marciojv,

Could you please rebase your branch with `origin/master`? 
It seems like your contribution is based on a rather old branch state.

Best,
Tassilo

**Comment by tasso94** [comment]
Hi @marciojv,

Are you still interested in pushing this PR forward? 
If I don't hear back from you in the next weeks, I'll have to close the PR.

Best,
Tassilo

**Comment by marciojv** [comment]
@tasso94 cancel this I send other PR.

**Pull request closed without merging**
